const TICKET_TYPES = ["ADULT", "CHILD", "INFANT"];
const TICKET_PRICES = {
  ADULT: 25,
  CHILD: 15,
  INFANT: 0,
};
const MAX_NUMBER_OF_TICKETS_PER_PURCHASE = 25;
const HTTP_STATUS_CODES = {
  BAD_REQUEST: 400,
  INTERNAL_SERVER_ERROR: 500,
  OK: 200,
  RESOURCE_NOT_FOUND: 404,
};
const STATUS_RESPONSES = {
  SUCCESS: "Success",
  FAILURE: "Failure",
};

export {
  TICKET_TYPES,
  TICKET_PRICES,
  MAX_NUMBER_OF_TICKETS_PER_PURCHASE,
  HTTP_STATUS_CODES,
  STATUS_RESPONSES,
};
